### ISSUE TITLE
Strings of UUID appear at the end of chat messages

### ISSUE THREAD

**Issue by nicklly** [LOOHP/InteractiveChat#52]
Sever: WateFall (BungeeCord} + paperspigot 1.12.2
plugins Version: 3.2.13.11

this is my config.yml https://pastebin.com/D4yqnvYJ

Have one day, I found that a string of UUID appears in the chat message when the player is chatting , Then when I tried to send the chat message again, the problem was solved.
When I deleted other plugins and then interactiveChat, 

before delete the InteractivChat plugins, like this 
![QQ截图20210405134638](https://user-images.githubusercontent.com/17716585/113541754-71a43a80-9615-11eb-9dba-3dccad3770a5.png)

After delet the interactiveChat plugins:
![13RH@D_3X0PPELS`(P16(CR](https://user-images.githubusercontent.com/17716585/113542188-571e9100-9616-11eb-935e-b50fee762f2f.png)

**Comment by LOOHP** [comment]
Which chat managing plugin do you use?
Also, I haven't heard of WateFall before, can you give me a link to that?

**Comment by nicklly** [comment]
VentureChat, and the watefall is bungeecord the link https://papermc.io/downloads#Waterfall

**Comment by LOOHP** [comment]
Oh, you mean Waterfall. Waterfall is a proxy, you cannot use InteractiveChat on that alone, it had to be installed on backend servers as well.
However, the config you've provided is from a backend server (Bukkit/Spigot etc.) and you had Bungeecord disabled in it as well.

Try installing InteractiveChat on Waterfall (The proxy) as well as the backend servers (Bukkit/Spigot etc.) and after the `Settings,Bungeecord` option set to true on the backend servers (Bukkit/Spigot)

**Comment by nicklly** [comment]
No. I disabled the InteractiveChatBungee for some reason,... I just wan to use for Bukkit/Spigot, Although I am a bungeeCord server

**Comment by nicklly** [comment]
Even though I don’t use bungeecord, it shouldn’t be a problem, but I don’t know why this problem occurs. :{

**Comment by LOOHP** [comment]
If you do not have cross-server chat channels, then your current setup should be fine.

However, if you do have cross-server chat channels and want the [item], [inv] etc to work across servers, you will need to have InteractiveChat installed on Bungeecord and all servers and have the Bungeecord option enabled. Otherwise, once your chat messages arrive at other servers, they won't be processed properly.

**Comment by nicklly** [comment]
I know.. But I have disabled interactiveChatBungee before, and no such problem happened.

**Comment by nicklly** [comment]
I test on my computer, the question I asked did not appear, but it appeared on my server 
![QQ截图20210405153750](https://user-images.githubusercontent.com/17716585/113550044-fd719300-9624-11eb-96bf-57a7f6078c27.png)

**Comment by LOOHP** [comment]
That is because on your computer, you can running an old version. On that version, the new method which uses the <chat=UUID> isn't implemented yet. That's why you can kinda do that. (Note that cross-server chat channel wouldn't work)

If you just don't want to install InteractiveChat on bungeecord and that you don't care that placeholders breaks other servers, you can disabled the Settings.UseAccurateSenderPraser option to false in the 3.2.13.11 config.

**Comment by nicklly** [comment]
ok. I try it. thank
